api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "auto-pricing"
type = "function"
uid = "cf4d1c7e-6f70-23bb-7a4f-07dc4df08fa436d3d6d5"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/run.graphql"
  export = "cart_transform_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/auto_pricing.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
